[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'NLKNguyen/papercolor-theme'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'tpope/vim-rails'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'reireias/vim-cheatsheet'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'myhere/vim-nodejs-complete'
